name: ASP.NET Core Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use Windows if Windows-specific steps are needed

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # Update to match BulkyBooks project version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore BulkyBookWeb.sln

      # Step 4: Build solution
      - name: Build solution
        run: dotnet build BulkyBookWeb.sln --no-restore --configuration Release

      # Step 5: Run unit tests
      - name: Run tests
        run: dotnet test BulkyBookWeb.sln --no-build --verbosity normal

      # Step 6: Publish application
      - name: Publish application
        run: dotnet publish BulkyBookWeb/BulkyBookWeb.csproj --configuration Release --output ./publish

      # Step 7: Upload build artifacts
      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: bulkybooks-publish
          path: ./publish
