name: .NET Desktop Workflow

on:
  # Trigger workflow on push or pull request to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest # .NET Desktop apps are built on Windows environments

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # Update based on your project’s target .NET version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build project
        run: dotnet build --no-restore --configuration Release

      # Step 5: Run unit tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      # Step 6: Publish the application
      - name: Publish application
        run: dotnet publish --configuration Release --output ./publish

      # Step 7: Upload build artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-app
          path: ./publish
