name: .NET Desktop Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # Adjust the version based on your project

      # Install dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the solution
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Run tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      # Publish the build artifacts
      - name: Publish artifacts
        if: success()
        run: |
          dotnet publish -c Release -o ./publish
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: ./publish
