release:
  needs: build
  runs-on: windows-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: application-build

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: "Release ${{ github.ref_name }}"
        body: "Automated release for build ${{ github.ref_name }}"
        draft: false
        prerelease: false
        files: ./output/*
