name: Build and Publish .NET Desktop App

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x' # Targeting .NET 6

      # Step 3: Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore
        shell: pwsh # Explicitly setting shell for Windows compatibility

      # Step 4: Build the solution
      - name: Build Solution
        run: dotnet build --configuration Release --no-restore
        shell: pwsh

      # Step 5: Run tests (if applicable)
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
        shell: pwsh

      # Step 6: Package application
      - name: Publish Application
        run: dotnet publish -c Release -o ./output
        shell: pwsh

      # Step 7: Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: application-build
          path: ./output

  release:
    needs: build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: application-build

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: "Release v${{ github.run_number }}"
          body: "Automated release for build ${{ github.run_number }}"
          draft: false
          prerelease: false
          files: ./output/*
