name: Build and Publish .NET Desktop App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*' # Trigger on versioned tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore Dependencies
        run: dotnet restore
        shell: pwsh

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore
        shell: pwsh

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
        shell: pwsh

      - name: Publish Application
        run: dotnet publish -c Release -o ./output
        shell: pwsh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: application-build
          path: ./output

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v') # Run for versioned tags

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: application-build

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Automated release for build ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: ./output/*
